package main

import "fmt"

// Shell completion.
//
// The scripts are generated by the binary rather than shipped as files for the
// same reason the shell wrappers are: the command surface has to track the CLI,
// and a checkout, a release binary, and an in-place self-update all have to
// agree about it. Nothing is installed automatically - the user writes the
// script into the file their shell already reads.

// topLevelCommands is the command list completion offers, in help order. It is
// the surface `ccbunshin --help` documents; the internal commands
// (resolve-provider, run) are deliberately absent, as they are from usageText.
var topLevelCommands = []string{
	"init", "create", "launch", "local", "global", "model", "list", "status",
	"doctor", "delete", "uninstall", "proxy", "completion", "update", "version", "help",
}

// bashCompletion completes the CLI. Bash sources every file in
// $BASH_COMPLETION_USER_DIR/completions, so installing it is a single write.
//
// Profile names come from `ccbunshin list` at completion time, so a profile
// created later completes without regenerating the script.
const bashCompletion = `# ccbunshin: bash completion for the CLI.
#
# Generated by "ccbunshin completion bash". Write it to
# $BASH_COMPLETION_USER_DIR/completions/ccbunshin (default
# ~/.local/share/bash-completion/completions/ccbunshin), which bash sources on
# startup. Re-sourcing replaces the function, so it is idempotent.
_ccbunshin() {
  local cur cmds profiles
  COMPREPLY=()
  cur=${COMP_WORDS[COMP_CWORD]}
  cmds='init create launch local global model list status doctor delete uninstall proxy completion update version help'
  case ${COMP_CWORD} in
    1)
      COMPREPLY=($(compgen -W "$cmds" -- "$cur"))
      return
      ;;
    2)
      case ${COMP_WORDS[1]} in
        init) COMPREPLY=($(compgen -W 'bash zsh tcsh' -- "$cur")) ;;
        completion) COMPREPLY=($(compgen -W 'bash zsh' -- "$cur")) ;;
        proxy) COMPREPLY=($(compgen -W 'init start stop restart status' -- "$cur")) ;;
        help) COMPREPLY=($(compgen -W "$cmds" -- "$cur")) ;;
        launch|model|status|doctor|delete|local|global)
          profiles=$(command ccbunshin list 2>/dev/null | cut -f1 -s)
          COMPREPLY=($(compgen -W "$profiles" -- "$cur"))
          ;;
      esac
      ;;
    *)
      case ${COMP_WORDS[1]} in
        create) COMPREPLY=($(compgen -f -- "$cur")) ;;
        local|global|proxy|update) COMPREPLY=($(compgen -W '--force --unset' -- "$cur")) ;;
        *) COMPREPLY=($(compgen -f -- "$cur")) ;;
      esac
      ;;
  esac
}
complete -F _ccbunshin ccbunshin
`

// zshCompletion is a completion script whose two entries are activated in two
// different ways, which is also why the whole script is safe to source.
//
//   - ccbunshin: the leading #compdef line is all compinit reads. Placed on
//     fpath it autoloads _ccbunshin, and sourced from an rc file the script
//     defines the function itself.
//   - claude: compinit never sees the rest of the file, so this entry is
//     registered only when the script is sourced. Sourcing also re-registers
//     ccbunshin, so the recommendation is to source it.
//
// Both entries go through compdef rather than autoload tags, so the script has
// no external dependency and behaves the same either way.
const zshCompletion = `#compdef ccbunshin
# ccbunshin: zsh completion for the CLI and for the project-aware "claude" wrapper.
#
# Generated by "ccbunshin completion zsh". Source it from .zshrc, after compinit
# has run (oh-my-zsh sources .zshrc after its own compinit):
#
#   source ~/.zsh/completions/_ccbunshin
#
# Sourcing registers both completions. Putting the file on fpath instead (with
# "fpath=(~/.zsh/completions $fpath)" before compinit) covers ccbunshin only:
# compinit reads the #compdef line and never runs the rest of the file, so the
# claude completion stays unregistered. The file is written so that either way
# works; re-running it replaces the definitions rather than nesting them.
_ccbunshin() {
  local context state line
  typeset -A opt_args
  local cmds profiles
  cmds=(
    'init:create the profile directory, or print a shell wrapper'
    'create:create a profile'
    'launch:run Claude Code with a profile'
    'local:show, set, or clear the directory-local profile'
    'global:show, set, or clear the global (default) profile'
    'model:set the default model for a profile'
    'list:list profiles'
    'status:show a profile path and model'
    'doctor:check a profile for missing keys'
    'delete:delete a profile'
    'uninstall:remove the shell hooks init installed'
    'proxy:manage the model-routed proxy'
    'completion:print a shell completion script'
    'update:update to the latest release'
    'version:print the binary version'
    'help:show help, or help for one command'
  )
  # "ccbunshin list" prints one tab-separated line per profile; -s drops the
  # WARN lines it prints for a profile it cannot parse.
  profiles=(${(f)"$(command ccbunshin list 2>/dev/null | cut -f1 -s)"})
  if (( CURRENT == 2 )); then
    _describe -t commands 'ccbunshin command' cmds
  elif (( CURRENT == 3 )); then
    case $words[2] in
      init) _values 'shell' bash zsh tcsh ;;
      completion) _values 'shell' bash zsh ;;
      proxy) _values 'proxy command' init start stop restart status ;;
      help) _describe -t commands 'ccbunshin command' cmds ;;
      launch|model|status|doctor|delete)
        (( ${#profiles} )) && _describe -t profiles 'profile' profiles
        ;;
      local|global)
        (( ${#profiles} )) && _describe -t profiles 'profile' profiles
        _values 'flag' --unset
        ;;
    esac
  else
    case $words[2] in
      create)
        _values 'flag' --force
        _files
        ;;
      local|global|proxy|update) _values 'flag' --force --unset ;;
      *) _files ;;
    esac
  fi
}
# compinit autoloads _ccbunshin from fpath when it dispatches on the file name;
# when the script is sourced instead, that call has already happened, so fill in
# the completion function compinit would have created.
if (( ! $+functions[ccbunshin] )); then
  functions[ccbunshin]=$functions[_ccbunshin]
fi
compdef _ccbunshin ccbunshin

# claude is registered only when this file is sourced, which is what the header
# above recommends. compinit, when it reads this file from fpath, looks at the
# #compdef line and stops - so the guard keeps the two paths consistent instead
# of leaving a stale binding behind from an earlier source.
if [[ -n ${ZSH_EVAL_CONTEXT%%:file*} && ${ZSH_EVAL_CONTEXT} == *:file* ]]; then
  # The wrapper makes claude a shell function inside a project and the real
  # binary outside one, and zsh cannot tell the two apart at completion time.
  # Alias expansion in _normal is what reaches that function.
  _claude() {
    local -a claude_opts
    claude_opts=(
      '(-c --continue)'{-c,--continue}'[continue the most recent conversation]'
      '(-r --resume)'{-r,--resume}'[resume a conversation]:session:'
      '--model[set the model for this session]:model:'
      '--settings[load settings from a JSON file]:file:_files'
      '(-p --print)'{-p,--print}'[print the response and exit]'
      '--help[print help]'
      '--version[print the version]'
      '*:prompt or file:_files'
    )
    _arguments -s $claude_opts
  }
  compdef _claude claude
fi
`

func completionScript(shell string) (string, error) {
	switch shell {
	case "bash":
		return bashCompletion, nil
	case "zsh":
		return zshCompletion, nil
	}
	return "", fmt.Errorf("unsupported shell %q (use bash or zsh)", shell)
}
